" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set guifont=Ubuntu\ Mono\ 7       " Set font
set guioptions-=r                 " Don't show right scrollbar
set lines=999 columns=999         " Start vim maximized

